_wandb:
    value:
        cli_version: 0.23.0
        e:
            pk1ojmpg1c5ydahtdkoxecbz3a1jkewi:
                codePath: c:\Users\emma\Documents\Land-Take-Prediction-Project-NINA-\notebooks\fc_early_fusion.ipynb
                codePathLocal: fc_early_fusion.ipynb
                cpu_count: 8
                cpu_count_logical: 8
                disk:
                    /:
                        total: "510770802688"
                        used: "352487575552"
                email: emma@gjoen.com
                executable: c:\Users\emma\Documents\Land-Take-Prediction-Project-NINA-\prosjekt_venv\Scripts\python.exe
                git:
                    commit: 2d700101aaead7fb5f737d25a02fa32307f6094b
                    remote: https://github.com/Ceciliamoller/Land-Take-Prediction-Project-NINA-.git
                host: YogaEmma
                memory:
                    total: "16505954304"
                os: Windows-11-10.0.26200-SP0
                program: c:\Users\emma\Documents\Land-Take-Prediction-Project-NINA-\notebooks\fc_early_fusion.ipynb
                python: CPython 3.13.9
                root: c:\Users\emma\Documents\Land-Take-Prediction-Project-NINA-\notebooks
                startedAt: "2025-11-18T16:11:59.801973Z"
                writerId: pk1ojmpg1c5ydahtdkoxecbz3a1jkewi
        m: []
        python_version: 3.13.9
        t:
            "1":
                - 1
                - 5
                - 53
            "2":
                - 1
                - 5
                - 53
            "3":
                - 2
                - 16
            "4": 3.13.9
            "5": 0.23.0
            "8":
                - 1
                - 3
            "12": 0.23.0
            "13": windows-amd64
architecture:
    value: FCEF
dataset:
    value: sentinel
epochs:
    value: 10
learning_rate:
    value: 0.001
